### ISSUE TITLE
It works in Linux, but not on Windows.

### ISSUE THREAD

**Issue by 1k-Element** [gavindsouza/inventory-management-system#1]
Please help me run this on Windows. A step-by-step will be a huge help. Thank you.

**Comment by gavindsouza** [comment]
Can you share where you're stuck? Steps should be pretty much the same as the ones mentioned in the README if you have `git` and `python3` installed correctly.

**Comment by magnooj** [comment]
Hi, after I run python -m flask run, I get these errors:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\magnooj\AppData\Roaming\Python\Python39\site-packages\flask\__main__.py", line 14, in <module>
    main(as_module=True)
  File "C:\Users\magnooj\AppData\Roaming\Python\Python39\site-packages\flask\cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "C:\Users\magnooj\AppData\Roaming\Python\Python39\site-packages\flask\cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "C:\Users\magnooj\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\magnooj\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\magnooj\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\magnooj\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\magnooj\AppData\Roaming\Python\Python39\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\magnooj\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\magnooj\AppData\Roaming\Python\Python39\site-packages\flask\cli.py", line 767, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "C:\Users\magnooj\AppData\Roaming\Python\Python39\site-packages\flask\cli.py", line 293, in __init__
    self._load_unlocked()
  File "C:\Users\magnooj\AppData\Roaming\Python\Python39\site-packages\flask\cli.py", line 317, in _load_unlocked
    self._app = rv = self.loader()
  File "C:\Users\magnooj\AppData\Roaming\Python\Python39\site-packages\flask\cli.py", line 376, in load_app
    app = locate_app(self, import_name, None,
  File "C:\Users\magnooj\AppData\Roaming\Python\Python39\site-packages\flask\cli.py", line 235, in locate_app
    __import__(module_name)
  File "D:\Libraries\Desktop\finalproject\inventory-management-system\inventory\app.py", line 14, in <module>
    app = Flask(__name__)
  File "C:\Users\magnooj\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 558, in __init__
    self.add_url_rule(
  File "C:\Users\magnooj\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 66, in wrapper_func
    return f(self, *args, **kwargs)
  File "C:\Users\magnooj\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 1216, in add_url_rule
    self.url_map.add(rule)
  File "C:\Users\magnooj\AppData\Roaming\Python\Python39\site-packages\werkzeug\routing.py", line 1386, in add
    rule.bind(self)
  File "C:\Users\magnooj\AppData\Roaming\Python\Python39\site-packages\werkzeug\routing.py", line 730, in bind
    self.compile()
  File "C:\Users\magnooj\AppData\Roaming\Python\Python39\site-packages\werkzeug\routing.py", line 794, in compile
    self._build = self._compile_builder(False).__get__(self, None)
  File "C:\Users\magnooj\AppData\Roaming\Python\Python39\site-packages\werkzeug\routing.py", line 945, in _compile_builder
    code = compile(module, "<werkzeug routing>", "exec")
TypeError: required field "type_ignores" missing from Module

Could you please help me?
Win 11, Using VScode and Powershell with miniconda
